keys:
  - &user_age_key age177snhrqfd422qgm8425pzhrzzc9tt3asymt96mmrlmfg784casrs27frau
  - &host_ssh_key age1sc0kpgelt969f8vcrnft060cccxwpp25pmz58vzts85ukepnkezszg0a2q

creation_rules:
  - path_regex: sops/secrets.yaml$
    key_groups:
      - age:
        - *user_age_key

  - path_regex: sops/secrets.os.yaml$
    key_groups:
      - age:
        - *host_ssh_key
        - *user_age_key
