keys:
  - &primary age177snhrqfd422qgm8425pzhrzzc9tt3asymt96mmrlmfg784casrs27frau
creation_rules:
  - path_regex: sops/secrets.yaml$
    key_groups:
      - age:
        - *primary

  - path_regex: sops/OBSIDIAN_REST_API_KEY.yaml$
    key_groups:
      - age:
        - *primary
