# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."lobe-chat" = {
    image = "lobehub/lobe-chat";
    environment = {
      "ACCESS_CODE" = "lobe66";
      "OPENAI_API_KEY" = "sk-xxxx";
      "OPENAI_PROXY_URL" = "https://api-proxy.com/v1";
    };
    ports = [
      "3210:3210/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lobe-chat"
      "--network=lobe-chat_default"
    ];
  };
  systemd.services."podman-lobe-chat" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-lobe-chat_default.service"
    ];
    requires = [
      "podman-network-lobe-chat_default.service"
    ];
    partOf = [
      "podman-compose-lobe-chat-root.target"
    ];
    wantedBy = [
      "podman-compose-lobe-chat-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-lobe-chat_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f lobe-chat_default";
    };
    script = ''
      podman network inspect lobe-chat_default || podman network create lobe-chat_default
    '';
    partOf = [ "podman-compose-lobe-chat-root.target" ];
    wantedBy = [ "podman-compose-lobe-chat-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-lobe-chat-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
