preload = /home/neko/Pictures/Iceland/adam-jang-MLKrf51NV8w-unsplash.jpg
wallpaper = DP-1,/home/neko/Pictures/Iceland/adam-jang-MLKrf51NV8w-unsplash.jpg
wallpaper = DP-2,/home/neko/Pictures/Iceland/adam-jang-MLKrf51NV8w-unsplash.jpg
wallpaper = HDMI-A-1,/home/neko/Pictures/Iceland/adam-jang-MLKrf51NV8w-unsplash.jpg
