#! /bin/sh

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-4 -d 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a mpv state=floating
bspc rule -a steam state=floating

pgrep sxhkd || sxhkd &
"$HOME"/.config/polybar/polybar.sh &
pgrep dunst || dunst &
nitrogen --restore &
xsetroot -xcf /nix/store/awf0dvvqr550nn34q4v2jjzjsh5s637h-volantes-cursors-2022-08-27/share/icons/volantes_light_cursors/cursors/left_ptr 32 &
xset r rate 325 70
xset m 0 0
