#! /bin/sh
xrandr --output DP-4 --pos 0x1080 --primary --output HDMI-0 --pos 322x0

pkill sxhkd
sxhkd &

bspc monitor DP-4 -d 5 6 7 8 9
bspc monitor HDMI-0 -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a mpv state=floating

"$HOME"/.config/polybar/polybar.sh &
nitrogen --restore &
xset r rate 325 70
